---
- hosts: datanodes
  vars:
    ansible_ssh_user: ec2-user
  tasks:
    - name: delete disk stores 
      become: no
      file: 
        path: "{{ item }}"
        state: absent
      loop:
        - /data/Accounts
        - /data/SecurityPrices
        - /data/pdx 