---
- hosts: grinder
  vars:
    ansible_ssh_user: ec2-user
  tasks:
    - name: install required software 
      become: yes
      yum: 
        name: ['java-1.8.0-openjdk']
    
    # - name: disable iptables
    #   become: yes
    #   service: 
    #     name: iptables
    #     enabled: no 
    #     state: stopped
    
    - name: create grinder directory
      become: no 
      file:
        dest: /runtime/grinder 
        state: directory

    - name: upload and unpack grinder  
      become: no
      unarchive:
        remote_src: no
        src: ../grinder-3.11-binary.zip
        dest: /runtime/grinder/
        creates: /runtime/grinder/grinder-3.11
        owner: ec2-user
        group: ec2-user
        
    - name: upload grinder files  
      become: no
      copy:
        remote_src: no
        src: grinder/
        dest: /runtime/grinder/
        owner: ec2-user
        group: ec2-user
