---
- hosts: grinder
  vars:
    ansible_ssh_user: ec2-user
  tasks:
    - name: launch grinder agents 
      become: no
      shell: cd /runtime/grinder;nohup java -cp grinder-3.11/lib/grinder.jar net.grinder.Grinder </dev/null >/dev/null 2>&1 &
    
