---
- hosts: 
    - datanodes
    - locators
  vars:
    ansible_ssh_user: ec2-user
  tasks:
    - name: copy application jars to runtime/lib folder 
      become: no
      copy: 
        src: resources/lib
        dest: /runtime
        owner: ec2-user 
        group: ec2-user

