# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs


PATH=/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/aws/bin:/runtime/gemfire/bin:/runtime/maven/bin

GEMFIRE=/runtime/gemfire
GF_JAVA=/usr/lib/jvm/java-11-openjdk-11.0.12.0.7-0.el7_9.x86_64/bin/java

export PATH
export GEMFIRE
export GF_JAVA

echo GF_JAVA environment variable set to $GF_JAVA
echo GEMFIRE environment variable set to $GEMFIRE
